# Generated by Django 5.2.8 on 2026-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_routeshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeshare',
            name='message',
            field=models.TextField(blank=True, default='dsadas', help_text='Optional message for recipient', verbose_name='Message'),
            preserve_default=False,
        ),
    ]
