# Generated by Django 5.2.8 on 2026-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_audio', '0003_alter_audiogeneration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiogeneration',
            name='error_message',
            field=models.TextField(blank=True, default='sewr', verbose_name='Error message'),
            preserve_default=False,
        ),
    ]
