# Generated by Django 5.2.8 on 2026-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_remove_route_mood_remove_route_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='country',
            field=models.CharField(blank=True, default='unknown country', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
